# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site settings


# User settings
username: LTM TECH
user_title: Software Developer
title: LTM Tech
email: Jhonescpereira@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Olá, Eu sou o Jhones. Quando eu e minha esposa decidimos que já era hora de vivermos a vida mais intensamente, percebemos que mesmo querendo muito sair para conhecer o mundo, estavamos presos em nosso empregos. Não podiamos decidir por nós mesmos o direito básico de todos cidadão o de ir e vir livremente. Por esse motivo decidimos deixar nossos empregos e nos dedicar mais a nossa vida. Porém, ainda precisamos comer, foi por isso que decidimos usar nossas habilidade e experiencias para forma nossa propria empresa. E foi pensando nesse nosso novo estilo de vida que optamos pelo nome LTM (live the moment), sim nós queremos viver ao maximo cada momento. Abaixo segue alguma das nossas competencias e contatos. Esperamos poder lhe ajudar e fazer não só negocios mas amigos! Forte abraço. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
